"""
seed.py — Deep Roots Archive
Seeds foundational historical records into the database.
Run once: python3 seed.py
"""
import os
os.environ.setdefault("DATABASE_URL", input("Paste your Neon DATABASE_URL: ").strip())

from repo.database import init_db, save_case

init_db()

SEEDS = [
  {
    "case_id":      "DRA-TULSA-1921",
    "record_type":  "massacre",
    "summary":      "Tulsa Race Massacre. The Greenwood District — Black Wall Street — was destroyed by a white mob over 18 hours on May 31–June 1, 1921. Up to 300 Black residents killed. 10,000 left homeless. 35 blocks burned to the ground. Homes, churches, schools, hospitals, and businesses destroyed. No criminal charges were ever filed. The state of Oklahoma did not formally acknowledge the massacre for 75 years.",
    "date":         "1921-05-31",
    "city":         "Tulsa",
    "state":        "OK",
    "lat":          36.1540,
    "lng":          -95.9928,
    "status":       "no_charges",
    "source_url":   "https://eji.org/news/tulsa-race-massacre/",
    "source_name":  "Equal Justice Initiative",
    "is_historical": True,
    "victim_race":  "Black",
  },
  {
    "case_id":      "DRA-ROSEWOOD-1923",
    "record_type":  "massacre",
    "summary":      "Rosewood Massacre. A prosperous Black town in Levy County, Florida was burned to the ground by a white mob in January 1923. At least 6 Black residents confirmed killed, possibly dozens more. Every Black-owned structure in the town was destroyed. Survivors fled into the swamps. The town was wiped from the map. The state of Florida did not acknowledge the massacre or provide reparations until 1994.",
    "date":         "1923-01-01",
    "city":         "Rosewood",
    "state":        "FL",
    "lat":          29.2572,
    "lng":          -82.8943,
    "status":       "no_charges",
    "source_url":   "https://www.floridamemory.com/learn/classroom/rosewood/",
    "source_name":  "Florida Memory",
    "is_historical": True,
    "victim_race":  "Black",
  },
  {
    "case_id":      "DRA-OSAGE-1920S",
    "record_type":  "massacre",
    "summary":      "Osage Indian Murders. After oil was discovered on Osage Nation land in Oklahoma in the 1920s, white men systematically murdered Osage people to steal their mineral rights through the guardianship system. At least 60 confirmed killings, likely hundreds more. Victims were poisoned, shot, and blown up. The FBI's first major homicide investigation. Most perpetrators were never prosecuted.",
    "date":         "1921-01-01",
    "city":         "Pawhuska",
    "state":        "OK",
    "lat":          36.6706,
    "lng":          -96.3394,
    "status":       "no_charges",
    "source_url":   "https://www.fbi.gov/history/famous-cases/osage-indian-murders",
    "source_name":  "FBI Famous Cases",
    "is_historical": True,
    "victim_race":  "Indigenous — Osage Nation",
  },
  {
    "case_id":      "DRA-ELAINE-1919",
    "record_type":  "massacre",
    "summary":      "Elaine Massacre. On September 30–October 1, 1919, white mobs and US Army troops attacked Black sharecroppers in Elaine, Arkansas who had organized a union. Between 100 and 800 Black residents were killed. Five white men also died. No white men were prosecuted. Twelve Black men were sentenced to death, later overturned by the Supreme Court in Moore v. Dempsey.",
    "date":         "1919-09-30",
    "city":         "Elaine",
    "state":        "AR",
    "lat":          34.3015,
    "lng":          -90.8457,
    "status":       "no_charges",
    "source_url":   "https://eji.org/reports/reconstruction-in-america-overview/",
    "source_name":  "Equal Justice Initiative",
    "is_historical": True,
    "victim_race":  "Black",
  },
  {
    "case_id":      "DRA-WILMINGTON-1898",
    "record_type":  "massacre",
    "summary":      "Wilmington Massacre. On November 10, 1898, a white supremacist mob overthrew the elected biracial government of Wilmington, North Carolina — the only successful coup d'état in American history. At least 60 Black residents were killed. Hundreds were expelled from the city. Black-owned businesses and the Black newspaper were burned. No one was prosecuted.",
    "date":         "1898-11-10",
    "city":         "Wilmington",
    "state":        "NC",
    "lat":          34.2257,
    "lng":          -77.9447,
    "status":       "no_charges",
    "source_url":   "https://eji.org/",
    "source_name":  "Equal Justice Initiative",
    "is_historical": True,
    "victim_race":  "Black",
  },
  {
    "case_id":      "DRA-MOVE-1985",
    "record_type":  "massacre",
    "summary":      "MOVE Bombing. On May 13, 1985, Philadelphia police dropped a bomb on a row house occupied by MOVE, a Black liberation organization. The bomb ignited a fire that city officials allowed to burn. 11 people were killed including 5 children. 61 homes were destroyed. No officers were charged. The city later demolished and rebuilt the homes negligently, triggering further legal action.",
    "date":         "1985-05-13",
    "city":         "Philadelphia",
    "state":        "PA",
    "lat":          39.9526,
    "lng":          -75.1652,
    "status":       "no_charges",
    "source_url":   "https://whyy.org/articles/move-bombing-philadelphia-1985/",
    "source_name":  "WHYY",
    "is_historical": False,
    "victim_race":  "Black",
  },
  {
    "case_id":      "DRA-EMMETT-TILL-1955",
    "record_type":  "lynching",
    "summary":      "Murder of Emmett Till. On August 28, 1955, 14-year-old Emmett Till, a Black teenager from Chicago, was abducted, tortured, and murdered in Money, Mississippi by Roy Bryant and J.W. Milam after Carolyn Bryant falsely accused him of whistling at her. Bryant and Milam were acquitted by an all-white jury in 67 minutes. They later confessed to the murder in a magazine interview. In 2022, Carolyn Bryant admitted she lied.",
    "date":         "1955-08-28",
    "city":         "Money",
    "state":        "MS",
    "lat":          33.6821,
    "lng":          -90.1954,
    "status":       "no_charges",
    "source_url":   "https://eji.org/news/emmett-till/",
    "source_name":  "Equal Justice Initiative",
    "is_historical": True,
    "victim_race":  "Black",
    "victim_name":  "Emmett Till",
    "victim_age":   "14",
  },
  {
    "case_id":      "DRA-GEORGE-FLOYD-2020",
    "record_type":  "police_killing",
    "summary":      "Murder of George Floyd. On May 25, 2020, Minneapolis police officer Derek Chauvin knelt on George Floyd's neck for 9 minutes and 29 seconds while Floyd was handcuffed and unresisting. Floyd died at the scene. Three other officers failed to intervene. Chauvin was convicted of murder in April 2021 and sentenced to 22.5 years. The killing sparked global protests.",
    "date":         "2020-05-25",
    "city":         "Minneapolis",
    "state":        "MN",
    "lat":          44.9374,
    "lng":          -93.2603,
    "status":       "convicted",
    "source_url":   "https://www.justice.gov/usao-mn/pr/derek-chauvin-sentenced-20-years-federal-civil-rights-charges",
    "source_name":  "DOJ",
    "is_historical": False,
    "victim_race":  "Black",
    "victim_name":  "George Floyd",
    "victim_age":   "46",
  },
  {
    "case_id":      "DRA-BREONNA-TAYLOR-2020",
    "record_type":  "police_killing",
    "summary":      "Killing of Breonna Taylor. On March 13, 2020, Louisville Metro Police officers executed a no-knock warrant at the apartment of Breonna Taylor, a 26-year-old Black emergency medical technician. Officers fired 32 rounds. Taylor was shot 5 times and killed. No drugs were found. No officers were charged with her death in state court. One federal officer was later convicted of civil rights violations.",
    "date":         "2020-03-13",
    "city":         "Louisville",
    "state":        "KY",
    "lat":          38.2527,
    "lng":          -85.7585,
    "status":       "no_charges",
    "source_url":   "https://www.justice.gov/usao-wdky/pr/former-louisville-metro-police-officer-convicted-federal-civil-rights-charges",
    "source_name":  "DOJ",
    "is_historical": False,
    "victim_race":  "Black",
    "victim_name":  "Breonna Taylor",
    "victim_age":   "26",
  },
  {
    "case_id":      "DRA-AHMAUD-ARBERY-2020",
    "record_type":  "hate_crime",
    "summary":      "Murder of Ahmaud Arbery. On February 23, 2020, Ahmaud Arbery, a 25-year-old Black man, was chased and shot to death while jogging in Brunswick, Georgia by Travis McMichael, Gregory McMichael, and William Bryan. The men pursued Arbery in pickup trucks and filmed his killing. No arrests were made for 74 days until the video was leaked. All three men were convicted of murder and federal hate crimes.",
    "date":         "2020-02-23",
    "city":         "Brunswick",
    "state":        "GA",
    "lat":          31.1499,
    "lng":          -81.4915,
    "status":       "convicted",
    "source_url":   "https://www.justice.gov/opa/pr/three-men-convicted-federal-hate-crimes-murder-ahmaud-arbery",
    "source_name":  "DOJ",
    "is_historical": False,
    "victim_race":  "Black",
    "victim_name":  "Ahmaud Arbery",
    "victim_age":   "25",
  },
  {
    "case_id":      "DRA-TRAYVON-MARTIN-2012",
    "record_type":  "hate_crime",
    "summary":      "Murder of Trayvon Martin. On February 26, 2012, Trayvon Martin, a 17-year-old Black teenager, was shot and killed by George Zimmerman in Sanford, Florida while walking home from a convenience store. Martin was unarmed. Zimmerman, a neighborhood watch volunteer, followed Martin against police dispatcher instructions. Zimmerman was acquitted of murder in 2013. The case sparked the founding of Black Lives Matter.",
    "date":         "2012-02-26",
    "city":         "Sanford",
    "state":        "FL",
    "lat":          28.8028,
    "lng":          -81.2731,
    "status":       "no_charges",
    "source_url":   "https://eji.org/news/trayvon-martin/",
    "source_name":  "Equal Justice Initiative",
    "is_historical": False,
    "victim_race":  "Black",
    "victim_name":  "Trayvon Martin",
    "victim_age":   "17",
  },
  {
    "case_id":      "DRA-ERIC-GARNER-2014",
    "record_type":  "police_killing",
    "summary":      "Killing of Eric Garner. On July 17, 2014, NYPD officer Daniel Pantaleo placed Eric Garner in a chokehold prohibited by department policy during an arrest for selling loose cigarettes on Staten Island, New York. Garner repeated 'I can't breathe' eleven times before losing consciousness. He was pronounced dead at the hospital. A grand jury declined to indict Pantaleo. He was fired five years later.",
    "date":         "2014-07-17",
    "city":         "Staten Island",
    "state":        "NY",
    "lat":          40.6280,
    "lng":          -74.0776,
    "status":       "no_charges",
    "source_url":   "https://eji.org/news/eric-garner/",
    "source_name":  "Equal Justice Initiative",
    "is_historical": False,
    "victim_race":  "Black",
    "victim_name":  "Eric Garner",
    "victim_age":   "43",
  },
]

saved = 0
for case in SEEDS:
    if save_case(case):
        saved += 1
        print(f"  Saved: {case['case_id']}")
    else:
        print(f"  Already exists: {case['case_id']}")

print(f"\nDone. {saved} new records seeded.")
